import dotenv from 'dotenv'; dotenv.config();
import mongoose from 'mongoose';
import fs from 'node:fs';
const base = process.env.MONGO_URI.replace(/\/[^/]*$/, '');
await mongoose.connect(`${base}/odito_visual_verify`);
const { default: User } = await import('./src/modules/user/model/User.js');
const { default: SeoProject } = await import('./src/modules/app_user/model/SeoProject.js');
const { signAuthToken } = await import('./src/modules/user/service/tokenService.js');
const user = await User.findOne({ email: /^visual-/ });
const project = await SeoProject.findOne({ user_id: user._id });
fs.writeFileSync(process.argv[2], JSON.stringify({ token: signAuthToken(user), projectId: String(project._id) }));
console.log('wrote', process.argv[2], String(project._id));
await mongoose.disconnect();
process.exit(0);
