import mongoose from 'mongoose';
import { ResponseUtil } from '../../../utils/ResponseUtil.js';
import { LoggerUtil } from '../../../utils/LoggerUtil.js';
import { JobService } from '../../jobs/service/jobService.js';
import JobDispatcher from '../../jobs/service/jobDispatcher.js';
import SeoProject from '../model/SeoProject.js';
import auditProgressService from '../../jobs/service/auditProgressService.js';
import fetch from 'node-fetch';
import Job from '../../jobs/model/Job.js';
import { startProjectAudit, AUDIT_RESULT_CODES, ACTIVE_PIPELINE_JOB_TYPES } from '../service/projectAuditService.js';
import {
  startUrlVerification as startUrlVerificationService,
  startVerificationBatch as startVerificationBatchService,
  URL_VERIFICATION_RESULT_CODES,
} from '../../verification/service/urlVerificationService.js';

// Get MongoDB connection to access collections directly
const getDb = () => mongoose.connection.db;

const jobService = new JobService();
// Remove global jobDispatcher instantiation - will be created in functions

// Debug: Verify Job model is imported
LoggerUtil.debug('Job model loaded', { type: typeof Job });

/**
 * Soft reset — clear only collections regenerated during verification.
 * Preserves discovery data (seo_internal_links, crawl graph, domain performance,
 * keyword research, technical reports) so Quick Recheck can reuse them.
 */
const softResetProjectCrawlData = async (projectId) => {
  try {
    const db = getDb();
    const { ObjectId } = mongoose.Types;
    const projectIdObj = new ObjectId(projectId);

    LoggerUtil.info(`Soft resetting verification data for project | projectId=${projectId}`);

    // Clear only collections regenerated by the verification pipeline.
    //
    // Preserved (never touched by Quick Recheck):
    //   seo_internal_links, seo_external_links, seo_social_links   — link discovery
    //   seo_crawl_graph                                             — crawl topology
    //   seo_domain_performance                                      — domain perf/pagespeed history
    //   seo_page_performance                                        — per-page pagespeed history
    //   seo_keyword_research, seo_keyword_opportunities             — keyword intelligence
    //   seo_rankings                                                — keyword ranking history
    //   search_console_data                                         — SERP tracking
    //   seo_first_snapshot, seo_mainurl_snapshot                    — audit snapshots
    //   audit_runs                                                  — audit history
    //
    // SEO collections (Node.js-written) use camelCase field 'projectId'.
    const collectionsToSoftClear = [
      'seo_page_data',     // regenerated by PAGE_SCRAPING
      'seo_page_issues',   // regenerated by PAGE_ANALYSIS
      'seo_page_scores',   // regenerated by SEO_SCORING
      'seo_page_summary',  // regenerated by SEO_SCORING
      'seo_headless_data', // regenerated by HEADLESS_ACCESSIBILITY
    ];

    // AI V2 collections (Python-written) use snake_case field 'project_id'.
    const aiV2CollectionsToSoftClear = [
      'ai_pages',
      'ai_scores',
      'ai_issues',
      'ai_projects',
    ];

    let totalDeleted = 0;
    for (const collectionName of collectionsToSoftClear) {
      const result = await db.collection(collectionName).deleteMany({ projectId: projectIdObj });
      totalDeleted += result.deletedCount;
      LoggerUtil.debug(`Soft cleared ${collectionName}`, { deleted: result.deletedCount });
    }
    for (const collectionName of aiV2CollectionsToSoftClear) {
      const result = await db.collection(collectionName).deleteMany({ project_id: projectIdObj });
      totalDeleted += result.deletedCount;
      LoggerUtil.debug(`Soft cleared ${collectionName}`, { deleted: result.deletedCount });
    }

    // 🔥 CRITICAL: Delete old Job records so the dependency gate does not find
    // stale PAGE_ANALYSIS jobs and silently skip creating new ones.
    const jobDeleteResult = await Job.deleteMany({ project_id: projectIdObj });
    totalDeleted += jobDeleteResult.deletedCount;
    LoggerUtil.info(`Soft reset: cleared old jobs`, { projectId, deleted: jobDeleteResult.deletedCount });

    // Reset verification-relevant project counters only
    await SeoProject.findByIdAndUpdate(projectId, {
      pages_crawled: 0,
      pages_analyzed: 0,
      total_issues: 0,
      crawl_status: 'pending',
      last_analysis_at: null
    });

    LoggerUtil.info(`Project soft reset complete`, { projectId, totalDeleted });
    return totalDeleted;

  } catch (error) {
    LoggerUtil.error(`Failed to soft reset crawl data`, error, { projectId });
    throw error;
  }
};

/**
 * Start the Quick Recheck (verification) pipeline.
 *
 * Skips LINK_DISCOVERY, URL_QUALIFICATION, DOMAIN_PERFORMANCE, KEYWORD_RESEARCH,
 * PERFORMANCE_MOBILE, and PERFORMANCE_DESKTOP. Reuses URLs from seo_internal_links.
 * Runs: PAGE_SCRAPING → CRAWL_GRAPH + AI_VISIBILITY, HEADLESS_ACCESSIBILITY,
 *       then PAGE_ANALYSIS → SEO_SCORING.
 */
export const startVerification = async (req, res) => {
  try {
    const jobDispatcher = new JobDispatcher();
    const { project_id } = req.body;

    if (!project_id) {
      return res.status(400).json({ success: false, message: 'project_id is required' });
    }

    const project = await SeoProject.findById(project_id);
    if (!project) {
      return res.status(404).json({ success: false, message: 'Project not found' });
    }

    // 🔒 SECURITY: Verify project ownership before starting verification
    if (project.user_id.toString() !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        message: 'Access denied: You do not own this project'
      });
    }

    // run_id: Quick Recheck mints its own fresh run_id too (per the approved
    // decision that verification mode stays single-job, no JobGroup/chunking,
    // but still gets run isolation). Stamped atomically alongside the claim.
    const runId = new mongoose.Types.ObjectId();

    // 🔒 ATOMIC IDEMPOTENCY GUARD: same pattern as startScraping
    const claimedProject = await SeoProject.findOneAndUpdate(
      { _id: project_id, crawl_status: { $nin: ['running'] } },
      { crawl_status: 'running', audit_started_at: new Date(), current_run_id: runId },
      { new: true }
    );

    if (!claimedProject) {
      return res.status(409).json({
        success: false,
        message: 'Scraping already in progress for this project'
      });
    }

    // Belt-and-suspenders: check for running verification jobs.
    // H3: reuses the shared ACTIVE_PIPELINE_JOB_TYPES (projectAuditService.js)
    // instead of this file's own narrower, previously-divergent list — now
    // also catches an in-flight Full Audit or URL Verification, not just
    // another legacy verification.
    const existingJobs = await jobService.getJobsByProject(project_id, {
      jobType: { $in: ACTIVE_PIPELINE_JOB_TYPES },
      status: { $in: ['pending', 'processing'] }
    });

    if (existingJobs.length > 0) {
      await SeoProject.findByIdAndUpdate(project_id, { crawl_status: project.crawl_status || 'pending' });
      return res.status(409).json({
        success: false,
        message: 'Verification already in progress for this project'
      });
    }

    // Load URLs from seo_page_data — these are pages that previously returned HTTP 200
    // and were successfully scraped. seo_internal_links may contain discovered-but-never-
    // scraped or dead URLs; seo_page_data is the authoritative set of live pages.
    const db = getDb();
    const { ObjectId } = mongoose.Types;
    const projectIdObj = new ObjectId(project_id);

    const pageDataDocs = await db.collection('seo_page_data')
      .find({ projectId: projectIdObj }, { projection: { url: 1 } })
      .toArray();

    const rawUrls = [...new Set(pageDataDocs.map(doc => doc.url).filter(Boolean))];

    if (rawUrls.length === 0) {
      await SeoProject.findByIdAndUpdate(project_id, { crawl_status: project.crawl_status || 'pending' });
      return res.status(400).json({
        success: false,
        code: 'NO_PREVIOUS_CRAWL',
        message: 'No previous crawl data found. Please run a Full Audit first.'
      });
    }

    // Always include project main URL; cap at 50 to bound worker load.
    // Normalize both sides before comparing — seo_page_data may store the homepage
    // with or without a trailing slash (e.g. "https://domain.com/" vs "https://domain.com"),
    // causing a strict .includes() to miss the match and inject both variants as separate URLs.
    const normalizeForCompare = (u) => u?.replace(/\/+$/, '').toLowerCase() ?? '';
    const normalizedMain = normalizeForCompare(project.main_url);
    const alreadyHasMain = rawUrls.some(u => normalizeForCompare(u) === normalizedMain);

    const withMain = alreadyHasMain
      ? rawUrls
      : [project.main_url, ...rawUrls];

    const finalUrls = withMain.slice(0, 50);

    LoggerUtil.info(`Starting verification for project | projectId=${project_id} | urls=${finalUrls.length}`);

    // Soft reset: clear verification-regenerated collections, preserve discovery data
    await softResetProjectCrawlData(project_id);

    // Create verification seed jobs — both receive the same canonical_urls list
    // so PAGE_SCRAPING and HEADLESS_ACCESSIBILITY process an identical URL set
    let pageScrapingJob, headlessA11yJob;
    try {
      pageScrapingJob = await jobService.createJob({
        user_id: req.user._id,
        seo_project_id: project_id,
        jobType: 'PAGE_SCRAPING',
        input_data: {
          mode: 'verification',
          canonical_urls: finalUrls,
          main_url: project.main_url
        },
        priority: 1,
        run_id: runId
      });

      headlessA11yJob = await jobService.createJob({
        user_id: req.user._id,
        seo_project_id: project_id,
        jobType: 'HEADLESS_ACCESSIBILITY',
        input_data: {
          mode: 'verification',
          canonical_urls: finalUrls,
          main_url: project.main_url,
          source_job_id: pageScrapingJob._id.toString()
        },
        priority: 1,
        run_id: runId
      });
    } catch (jobCreationError) {
      LoggerUtil.error('Verification job creation failed, releasing project lock', jobCreationError, { project_id });
      await SeoProject.findByIdAndUpdate(project_id, { crawl_status: project.crawl_status || 'pending' });
      throw jobCreationError;
    }

    // Mark project active
    await SeoProject.findByIdAndUpdate(project_id, { status: 'active' });

    // Dispatch both seed jobs asynchronously
    jobDispatcher.dispatchPageScrapingJob(pageScrapingJob).catch(error => {
      LoggerUtil.error(`Failed to dispatch PAGE_SCRAPING verification job ${pageScrapingJob._id}`, error);
    });

    jobDispatcher.dispatchHeadlessAccessibilityJob(headlessA11yJob).catch(error => {
      LoggerUtil.error(`Failed to dispatch HEADLESS_ACCESSIBILITY verification job ${headlessA11yJob._id}`, error);
    });

    // Emit started events so the frontend receives real-time updates
    auditProgressService.emitStarted(pageScrapingJob._id.toString(), {
      job_id: pageScrapingJob._id,
      job_type: pageScrapingJob.jobType,
      project_id,
      main_url: project.main_url,
      user_id: req.user._id,
      mode: 'verification'
    });

    auditProgressService.emitStarted(headlessA11yJob._id.toString(), {
      job_id: headlessA11yJob._id,
      job_type: headlessA11yJob.jobType,
      project_id,
      main_url: project.main_url,
      user_id: req.user._id,
      mode: 'verification'
    });

    return res.status(201).json({
      success: true,
      message: 'Quick Recheck started',
      data: {
        mode: 'verification',
        jobs: [
          {
            job_id: pageScrapingJob._id,
            job_type: pageScrapingJob.jobType,
            status: pageScrapingJob.status
          },
          {
            job_id: headlessA11yJob._id,
            job_type: headlessA11yJob.jobType,
            status: headlessA11yJob.status
          }
        ],
        url_count: finalUrls.length,
        project_id,
        main_url: project.main_url
      }
    });

  } catch (error) {
    LoggerUtil.error('Error starting verification pipeline', error, { project_id: req.body.project_id });
    return res.status(500).json(ResponseUtil.error('Failed to start verification pipeline', 500));
  }
};

/**
 * Start a URL Verification run (single-page recheck).
 *
 * This is a thin HTTP wrapper — all URL Verification logic (project
 * resolution, ownership check, URL validation, duplicate-run protection,
 * PageVerificationRun/job creation, dispatch) lives in
 * urlVerificationService.startUrlVerification(). Do not re-add any of that
 * logic here, matching the exact pattern startScraping() above uses for
 * startProjectAudit().
 */
export const startUrlVerification = async (req, res) => {
  const { projectId, url, options = {} } = req.body;

  try {
    if (!projectId || !url) {
      return res.status(400).json({
        success: false,
        message: 'projectId and url are required'
      });
    }

    // requestingUserId always comes from the authenticated session (auth
    // middleware), never from client-supplied `options` — options is
    // accepted per the request contract but the service does not currently
    // read anything else from it.
    const result = await startUrlVerificationService(projectId, url, {
      ...options,
      requestingUserId: req.user._id,
    });

    if (!result.success) {
      switch (result.code) {
        case URL_VERIFICATION_RESULT_CODES.NOT_FOUND:
          return res.status(404).json({ success: false, message: result.message });
        case URL_VERIFICATION_RESULT_CODES.ACCESS_DENIED:
          return res.status(403).json({ success: false, message: result.message });
        case URL_VERIFICATION_RESULT_CODES.INVALID_URL:
          return res.status(400).json({ success: false, message: result.message });
        case URL_VERIFICATION_RESULT_CODES.ALREADY_RUNNING:
          return res.status(409).json({ success: false, message: result.message });
        default:
          return res.status(500).json(ResponseUtil.error('Failed to start URL verification', 500));
      }
    }

    return res.status(201).json({
      success: true,
      message: 'URL Verification started',
      data: result.data,
    });

  } catch (error) {
    LoggerUtil.error('Error starting URL verification', error, { projectId, url });
    return res.status(500).json(ResponseUtil.error('Failed to start URL verification', 500));
  }
};

/**
 * Start a Verification Batch (F4-013 — API and creation infrastructure
 * only; no jobs, no dispatch, no orchestration yet).
 *
 * Thin HTTP wrapper — all logic lives in
 * urlVerificationService.startVerificationBatch(), matching the exact
 * pattern startUrlVerification() above uses. The response shape is flat
 * (no `data` wrapper) per this endpoint's own contract, unlike the
 * single-URL endpoint's `{success, message, data}` shape.
 */
export const startVerificationBatch = async (req, res) => {
  const { projectId, urls } = req.body;

  try {
    if (!projectId || !Array.isArray(urls) || urls.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'projectId and a non-empty urls array are required'
      });
    }

    const result = await startVerificationBatchService(projectId, urls, {
      requestingUserId: req.user._id,
    });

    if (!result.success) {
      switch (result.code) {
        case URL_VERIFICATION_RESULT_CODES.NOT_FOUND:
          return res.status(404).json({ success: false, message: result.message });
        case URL_VERIFICATION_RESULT_CODES.ACCESS_DENIED:
          return res.status(403).json({ success: false, message: result.message });
        case URL_VERIFICATION_RESULT_CODES.ALREADY_RUNNING:
          return res.status(409).json({ success: false, message: result.message });
        case URL_VERIFICATION_RESULT_CODES.NO_VALID_URLS:
          return res.status(400).json({ success: false, message: result.message, rejected: result.data?.rejected || [] });
        default:
          return res.status(500).json(ResponseUtil.error('Failed to start verification batch', 500));
      }
    }

    return res.status(201).json({
      success: true,
      ...result.data,
    });

  } catch (error) {
    LoggerUtil.error('Error starting verification batch', error, { projectId, urlCount: urls?.length });
    return res.status(500).json(ResponseUtil.error('Failed to start verification batch', 500));
  }
};

/**
 * Start the new scraping pipeline (manual "Recrawl Project" trigger).
 *
 * This is a thin HTTP wrapper — all audit-start logic (ownership check,
 * atomic crawl_status guard, duplicate-job guard, credit deduction, job
 * creation/dispatch) lives in startProjectAudit() so the Weekly Recrawl
 * scheduler can call the exact same implementation. Do not re-add any of
 * that logic here.
 */
export const startScraping = async (req, res) => {
  const { project_id } = req.body;

  try {
    if (!project_id) {
      return res.status(400).json({
        success: false,
        message: 'project_id is required'
      });
    }

    const result = await startProjectAudit(project_id, {
      source: 'manual',
      requestingUserId: req.user._id,
    });

    if (!result.success) {
      switch (result.code) {
        case AUDIT_RESULT_CODES.NOT_FOUND:
          return res.status(404).json({ success: false, message: result.message });
        case AUDIT_RESULT_CODES.ACCESS_DENIED:
          return res.status(403).json({ success: false, message: result.message });
        case AUDIT_RESULT_CODES.ALREADY_RUNNING:
          return res.status(409).json({
            success: false,
            message: result.message,
            ...(result.existing_job ? { existing_job: result.existing_job } : {}),
          });
        default:
          return res.status(500).json(ResponseUtil.error('Failed to start scraping pipeline', 500));
      }
    }

    return res.status(201).json({
      success: true,
      message: 'Your crawling has started',
      data: result.data,
    });

  } catch (error) {
    LoggerUtil.error('Error starting scraping pipeline', error, { project_id });
    return res.status(500).json(ResponseUtil.error('Failed to start scraping pipeline', 500));
  }
};

/**
 * Cancel running audit for a project
 */
export const cancelAudit = async (req, res) => {
  LoggerUtil.info('Cancel audit API called', { body: req.body });

  try {
    const { project_id, job_id } = req.body; // Accept both project_id and job_id

    if (!project_id && !job_id) {
      LoggerUtil.warn('Missing project_id or job_id');
      return res.status(400).json(ResponseUtil.error('project_id or job_id is required', 400));
    }

    // 🔒 SECURITY: Verify project ownership before cancelling
    if (project_id) {
      const project = await SeoProject.findById(project_id);
      if (!project) {
        return res.status(404).json(ResponseUtil.error('Project not found', 404));
      }
      if (project.user_id.toString() !== req.user._id.toString()) {
        return res.status(403).json(ResponseUtil.error('Access denied: You do not own this project', 403));
      }
    }

    let runningJobs = [];

    if (job_id) {
      // Cancel specific job by job_id (preferred)
      LoggerUtil.debug(`Looking for specific job: ${job_id}`);
      const job = await Job.findById(job_id);
      if (job && ['PROCESSING', 'QUEUED', 'CLAIMED'].includes(job.status)) {
        runningJobs = [job];
      }
    } else {
      // Legacy: find all running jobs for project
      LoggerUtil.debug(`Looking for running jobs in project: ${project_id}`);

      // First, let's see ALL jobs for this project for debugging
      const allJobs = await jobService.getJobsByProject(project_id, {});
      LoggerUtil.debug(`ALL jobs for project ${project_id}`, allJobs.map(j => ({
        id: j._id,
        status: j.status,
        jobType: j.jobType,
        project_id: j.project_id
      })));

      // Find running jobs for this project (PROCESSING, QUEUED, CLAIMED)
      runningJobs = allJobs.filter(job =>
        ['PROCESSING', 'QUEUED', 'CLAIMED'].includes(job.status)
      );
    }

    LoggerUtil.debug(`Found ${runningJobs.length} running jobs`, runningJobs.map(j => ({ id: j._id, status: j.status })));

    if (runningJobs.length === 0) {
      LoggerUtil.warn('No running jobs found');
      return res.status(404).json(ResponseUtil.error('No running jobs found for this project', 404));
    }

    // Mark jobs as cancelled in database
    const jobIds = runningJobs.map(job => job._id);
    LoggerUtil.debug(`Marking jobs as cancelled`, { jobIds });

    for (const jobId of jobIds) {
      await jobService.updateJobStatus(jobId, 'failed', {
        error_message: 'Audit cancelled by user',
        failed_at: new Date()
      });
    }

    LoggerUtil.info('Jobs marked as cancelled in database');

    // Notify Python workers to stop processing these jobs
    const pythonWorkerUrl = process.env.PYTHON_WORKER_URL;
    if (!pythonWorkerUrl) {
      throw new Error('PYTHON_WORKER_URL environment variable is required');
    }
    LoggerUtil.debug(`Notifying Python worker at: ${pythonWorkerUrl}`);

    for (const jobId of jobIds) {
      try {
        LoggerUtil.debug(`Sending cancel request for job: ${jobId}`);
        
        // Forward Authorization header to Python worker
        const headers = { 'Content-Type': 'application/json' };
        if (req.headers.authorization) {
          headers.Authorization = req.headers.authorization;
        }
        
        const response = await fetch(`${pythonWorkerUrl}/jobs/cancel`, {
          method: 'POST',
          headers,
          body: JSON.stringify({ jobId: jobId.toString() })
        });

        if (response.ok) {
          LoggerUtil.debug(`Notified Python worker to cancel job: ${jobId}`);
        } else {
          LoggerUtil.error(`Failed to notify Python worker for job ${jobId}`, { status: response.statusText });
        }
      } catch (workerError) {
        LoggerUtil.error(`Error notifying Python worker for job ${jobId}`, { message: workerError.message });
      }
    }

    // Emit cancellation event to frontend via auditProgressService
    runningJobs.forEach(job => {
      auditProgressService.emitError(job._id.toString(), {
        jobId: job._id,
        message: 'Audit cancelled by user',
        subtext: 'The audit was stopped by the user',
        error: 'USER_CANCELLED'
      });
    });

    // Update project status back to draft
    if (project_id) {
      await SeoProject.findByIdAndUpdate(project_id, {
        status: 'draft',
        crawl_status: 'cancelled'
      });
    }

    LoggerUtil.info(`User cancelled audit`, { jobIds });

    return res.json(ResponseUtil.success({
      cancelledJobs: jobIds,
      project_id
    }, 'Audit cancelled successfully'));

  } catch (error) {
    LoggerUtil.error('Error cancelling audit', error);
    return res.status(500).json(ResponseUtil.error('Failed to cancel audit', 500));
  }
};

/**
 * Get scraping status for a project
 */
export const getScrapingStatus = async (req, res) => {
  try {
    // Project ownership already verified by validateProjectAccess middleware
    const project_id = req.params.id;

    // Scope by the project's current run so a stale job from a superseded
    // run (e.g. incomplete cleanup, or genuinely still-finishing chunk work
    // in a future chunked stage) can never be counted alongside the run
    // that's actually live, which would otherwise let a completed status
    // from an old run mask a new run's still-in-progress state.
    const project = await SeoProject.findById(project_id).select('current_run_id crawl_status').lean();
    const currentRunId = project?.current_run_id || null;

    const jobs = await jobService.getJobsByProject(
      project_id,
      currentRunId ? { run_id: currentRunId } : {}
    );

    // All pipeline job types — update this list when adding new stages
    const PIPELINE_JOB_TYPES = [
      'link_discovery',
      'domain_performance',
      'technical_domain',
      'page_scraping',
      'headless_accessibility',
      'crawl_graph',
      'performance_mobile',
      'performance_desktop',
      'page_analysis',
      'seo_scoring',
      'ai_visibility',
      'ai_visibility_scoring'
    ];

    // Dynamically build the status object from the list
    const status = {};
    PIPELINE_JOB_TYPES.forEach(type => {
      status[type] = { pending: 0, processing: 0, completed: 0, failed: 0, latest: null };
    });

    jobs.forEach(job => {
      const key = job.jobType.toLowerCase();
      // Defensive: job.status is normally already lowercase (enforced in
      // jobService.updateJobStatus), but this counts case-insensitively too
      // so any stray/pre-existing record with an uppercase status (e.g. jobs
      // written before that normalization existed) still counts correctly
      // instead of silently vanishing from the response the frontend polls.
      const normalizedJobStatus = typeof job.status === 'string' ? job.status.toLowerCase() : job.status;
      if (status[key] && status[key][normalizedJobStatus] !== undefined) {
        status[key][normalizedJobStatus]++;
        if (!status[key].latest || new Date(job.created_at) > new Date(status[key].latest.created_at)) {
          status[key].latest = {
            job_id: job._id,
            status: normalizedJobStatus,
            created_at: job.created_at,
            completed_at: job.completed_at,
            failed_at: job.failed_at
          };
        }
      }
    });

    res.json({
      success: true,
      data: status,
      // Sibling of `data`, not merged into it — `data` must stay pure
      // job-type buckets since frontend callers do Object.values(data)
      // expecting every entry to be a {pending,processing,completed,failed}
      // shape. Surfaced so pollers (ProcessingScreen) can detect the
      // 'awaiting_url_selection' pause without a second API call — job-type
      // buckets alone can't represent it (no PAGE_SCRAPING/
      // HEADLESS_ACCESSIBILITY job exists yet while a project is parked in
      // that state).
      crawl_status: project?.crawl_status || null
    });

  } catch (error) {
    LoggerUtil.error('Error getting scraping status', error, { project_id: req.params.project_id });
    return res.status(500).json(ResponseUtil.error('Failed to get scraping status', 500));
  }
};

/**
 * Get raw HTML for a specific URL from stored page data
 */
export const getPageRawHtml = async (req, res) => {
  try {
    const { url, project_id } = req.query;

    if (!url) {
      return res.status(400).json({
        success: false,
        message: 'URL parameter is required'
      });
    }

    // 🔒 SECURITY: Require project_id to prevent cross-project data leakage
    if (!project_id) {
      return res.status(400).json({
        success: false,
        message: 'project_id parameter is required'
      });
    }

    // 🔒 SECURITY: Verify project ownership
    const project = await SeoProject.findById(project_id);
    if (!project || project.user_id.toString() !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        message: 'Access denied'
      });
    }

    LoggerUtil.debug(`Fetching raw HTML from stored data for URL: ${url}`);

    // Get the page data from seo_page_data collection — scoped by projectId
    // Projection: only fetch raw_html + timestamps; avoids loading the full document
    const db = getDb();
    const { ObjectId } = mongoose.Types;
    const pageData = await db.collection('seo_page_data').findOne(
      { url: url, projectId: new ObjectId(project_id) },
      { projection: { raw_html: 1, scrapedAt: 1, scraped_at: 1, _id: 0 } }
    );

    if (!pageData) {
      return res.status(404).json({
        success: false,
        message: 'Page data not found for this URL'
      });
    }

    // Check if HTML content exists in the stored data (field is raw_html)
    if (!pageData.raw_html) {
      return res.status(404).json({
        success: false,
        message: 'HTML content not found for this URL'
      });
    }

    LoggerUtil.debug(`Found HTML for ${url}`, { length: pageData.raw_html.length });

    res.json({
      success: true,
      data: {
        html: pageData.raw_html,
        url: url,
        fetched_at: pageData.scrapedAt || pageData.scraped_at || new Date().toISOString()
      }
    });

  } catch (error) {
    LoggerUtil.error(`Error getting raw HTML for ${req.query.url}`, error);
    return res.status(500).json(ResponseUtil.error('Failed to get HTML from stored data', 500));
  }
};
