import mongoose from 'mongoose';

/**
 * Google Ads Budget Alert Model
 *
 * One row per (project, customer, campaign, alert type) — generated by
 * googleAdsBudgetService during the sync's "generating_budget_alerts"
 * stage, purely from already-synced data (GoogleAdsCampaign.budget +
 * GoogleAdsCampaignMetrics), never a new Google API call. Upserted by
 * (campaign, alert_type) so a still-firing alert updates in place (its
 * `details`/`severity` refresh, `triggered_at` stays the ORIGINAL trigger
 * time) rather than spamming a new row every sync, and is marked
 * `is_resolved` the moment a later sync no longer detects the condition -
 * this is the "Duplicate Protection" this model needs, per Phase 6.5's
 * Production Hardening requirement.
 */

const googleAdsBudgetAlertSchema = new mongoose.Schema({
  project_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'SeoProject',
    required: [true, 'Project ID is required'],
    index: true
  },

  google_ads_customer_id: {
    type: String,
    required: [true, 'Google Ads customer ID is required'],
    trim: true
  },

  campaign_id: { type: String, required: [true, 'Campaign ID is required'], trim: true },
  campaign_name: { type: String, default: null },

  alert_type: {
    type: String,
    enum: ['overspend', 'underspend', 'budget_depleted', 'projected_overspend', 'no_budget_set'],
    required: [true, 'Alert type is required']
  },

  severity: {
    type: String,
    enum: ['info', 'warning', 'critical'],
    default: 'info'
  },

  message: { type: String, required: [true, 'Alert message is required'] },

  details: { type: mongoose.Schema.Types.Mixed, default: null }, // e.g. { budgetAmount, avgDailySpend, utilization, projectedMonthlySpend }

  is_resolved: { type: Boolean, default: false, index: true },
  triggered_at: { type: Date, default: Date.now },
  last_seen_at: { type: Date, default: Date.now },
  resolved_at: { type: Date, default: null }

}, {
  timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
  collection: 'google_ads_budget_alerts'
});

googleAdsBudgetAlertSchema.index(
  { project_id: 1, google_ads_customer_id: 1, campaign_id: 1, alert_type: 1 },
  { unique: true, name: 'unique_project_customer_campaign_alert_type' }
);

googleAdsBudgetAlertSchema.index({ project_id: 1, google_ads_customer_id: 1, is_resolved: 1 }, { name: 'project_customer_resolved' });

/**
 * Upserts the current set of active alerts and resolves any previously-
 * active alert not in this run's set (same "reconcile against current
 * truth" shape as GoogleAdsCampaign.markMissingAsRemoved).
 */
googleAdsBudgetAlertSchema.statics.reconcileAlerts = async function (projectId, customerId, activeAlerts) {
  const now = new Date();

  if (activeAlerts.length) {
    const bulkOps = activeAlerts.map((alert) => ({
      updateOne: {
        filter: { project_id: projectId, google_ads_customer_id: customerId, campaign_id: alert.campaignId, alert_type: alert.alertType },
        update: {
          $set: {
            campaign_name: alert.campaignName,
            severity: alert.severity,
            message: alert.message,
            details: alert.details,
            is_resolved: false,
            resolved_at: null,
            last_seen_at: now,
            updated_at: now
          },
          $setOnInsert: { triggered_at: now, created_at: now }
        },
        upsert: true
      }
    }));
    await this.bulkWrite(bulkOps, { ordered: false });
  }

  const activeKeys = activeAlerts.map((a) => `${a.campaignId}:${a.alertType}`);
  const candidates = await this.find(
    { project_id: projectId, google_ads_customer_id: customerId, is_resolved: false },
    { campaign_id: 1, alert_type: 1 }
  ).lean();
  const idsToResolve = candidates.filter((c) => !activeKeys.includes(`${c.campaign_id}:${c.alert_type}`)).map((c) => c._id);

  if (idsToResolve.length) {
    await this.updateMany({ _id: { $in: idsToResolve } }, { $set: { is_resolved: true, resolved_at: now } });
  }

  return { active: activeAlerts.length, resolved: idsToResolve.length };
};

googleAdsBudgetAlertSchema.statics.getActiveAlerts = async function (projectId, customerId) {
  return this.find({ project_id: new mongoose.Types.ObjectId(projectId), google_ads_customer_id: customerId, is_resolved: false })
    .sort({ severity: -1, triggered_at: -1 })
    .lean();
};

googleAdsBudgetAlertSchema.set('toJSON', { virtuals: true, transform: (doc, ret) => { delete ret.__v; return ret; } });
googleAdsBudgetAlertSchema.set('toObject', { virtuals: true });

const GoogleAdsBudgetAlert = mongoose.model('GoogleAdsBudgetAlert', googleAdsBudgetAlertSchema);
export default GoogleAdsBudgetAlert;
