import mongoose from 'mongoose';
import crypto from 'crypto';

/**
 * Field-level encryption for refresh_token / access_token.
 *
 * AES-256-GCM with a random IV per value. Ciphertext is stored as
 * `enc:v1:<iv-hex>:<authTag-hex>:<data-hex>` so legacy plaintext rows (no
 * prefix) are still readable as-is during migration, and re-encrypting an
 * already-encrypted value is a safe no-op (guards against double-encryption
 * if Mongoose ever applies this setter twice on the same write).
 */
const ENCRYPTION_ALGORITHM = 'aes-256-gcm';
const ENCRYPTION_PREFIX = 'enc:v1:';

function getEncryptionKey() {
  const keyHex = process.env.GOOGLE_TOKEN_ENCRYPTION_KEY;
  if (!keyHex || keyHex.length !== 64) {
    throw new Error('GOOGLE_TOKEN_ENCRYPTION_KEY must be set to a 64-character hex string (32 bytes)');
  }
  return Buffer.from(keyHex, 'hex');
}

export function encryptToken(plainText) {
  if (plainText === null || plainText === undefined || plainText === '') return plainText;
  if (typeof plainText === 'string' && plainText.startsWith(ENCRYPTION_PREFIX)) return plainText;

  const key = getEncryptionKey();
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv(ENCRYPTION_ALGORITHM, key, iv);
  const encrypted = Buffer.concat([cipher.update(String(plainText), 'utf8'), cipher.final()]);
  const authTag = cipher.getAuthTag();

  return `${ENCRYPTION_PREFIX}${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted.toString('hex')}`;
}

export function decryptToken(cipherText) {
  if (!cipherText || typeof cipherText !== 'string' || !cipherText.startsWith(ENCRYPTION_PREFIX)) {
    // Not encrypted (legacy plaintext row, or null/empty) - return as-is.
    return cipherText;
  }

  try {
    const [ivHex, authTagHex, dataHex] = cipherText.slice(ENCRYPTION_PREFIX.length).split(':');
    const key = getEncryptionKey();
    const decipher = crypto.createDecipheriv(ENCRYPTION_ALGORITHM, key, Buffer.from(ivHex, 'hex'));
    decipher.setAuthTag(Buffer.from(authTagHex, 'hex'));
    const decrypted = Buffer.concat([decipher.update(Buffer.from(dataHex, 'hex')), decipher.final()]);
    return decrypted.toString('utf8');
  } catch (error) {
    console.error('[GOOGLE_CONNECTION] Failed to decrypt token:', error.message);
    return null;
  }
}

/**
 * Shared shape for every entry in google_ads_capabilities (Gap #8). A
 * factory function rather than one object literal reused by reference,
 * since Mongoose subdocument definitions must not be the same object
 * instance shared across multiple schema paths.
 */
function capabilityFieldSchema() {
  return {
    supported: { type: Boolean, default: false },
    reason: { type: String, default: null },
    requiredPermission: { type: String, default: null },
    requiresSync: { type: Boolean, default: true },
    availableSince: { type: Date, default: null }
  };
}

const googleConnectionSchema = new mongoose.Schema({
  // 🔐 Primary key (auto-generated by MongoDB)
  // _id: ObjectId (implicit)

  // 👤 Connection owner
  user_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'User ID is required'],
    index: true
  },

  // 📌 Project association
  project_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'SeoProject',
    required: [true, 'Project ID is required'],
    index: true
  },

  // 🎯 Connection purpose
  // 'google_ads' is a deliberately separate purpose from 'google_visibility'
  // (not a 4th service_type on the existing bundle) so that adding Google
  // Ads never forces existing Search Console/Analytics/Business Profile
  // connections to re-consent to a new scope. Same model, same encryption,
  // same refresh flow — just its own row per (user_id, project_id), matching
  // the compound unique index below.
  purpose: {
    type: String,
    required: [true, 'Purpose is required'],
    enum: ['google_visibility', 'google_ads'],
    default: 'google_visibility'
  },

  // � Google services enabled for this connection
  service_type: {
    type: [String],
    enum: ['search_console', 'analytics', 'business_profile', 'google_ads'],
    default: [],
    validate: {
      validator: function(serviceTypes) {
        // Ensure no duplicates
        return serviceTypes.length === new Set(serviceTypes).size;
      },
      message: 'Service types must be unique'
    }
  },

  // 🔄 Last successful data sync timestamp
  last_sync_at: {
    type: Date,
    default: null
  },

  // 🔍 Search Console site URL (required when search_console service is enabled).
  // Stores the exact siteUrl string Google returned from sites.list — either
  // a URL-prefix property ("https://example.com/") or a domain property
  // ("sc-domain:example.com") — never reconstructed, always the verbatim
  // value the user selected from getSearchConsoleSites().
  search_console_site_url: {
    type: String,
    required: false, // Only required when search_console service is enabled
    validate: {
      validator: function(v) {
        if (this.service_type && this.service_type.includes('search_console')) {
          return v && v.trim().length > 0;
        }
        return true;
      },
      message: 'Search Console site URL is required when Search Console service is enabled'
    },
    trim: true
  },

  // 📊 Analytics property ID (required when analytics service is enabled)
  analytics_property_id: {
    type: String,
    required: false, // Only required when analytics service is enabled
    validate: {
      validator: function(v) {
        // If analytics is enabled, property_id must be present and non-empty
        if (this.service_type && this.service_type.includes('analytics')) {
          return v && v.trim().length > 0;
        }
        return true;
      },
      message: 'Analytics property ID is required when Analytics service is enabled'
    },
    trim: true
  },

  // 🏢 Business Profile Account ID (required when business_profile service is enabled)
  business_account_id: {
    type: String,
    required: false, // Only required when business_profile service is enabled
    validate: {
      validator: function(v) {
        // If business_profile is enabled, account_id must be present and non-empty
        if (this.service_type && this.service_type.includes('business_profile')) {
          return v && v.trim().length > 0;
        }
        return true;
      },
      message: 'Business Profile account ID is required when Business Profile service is enabled'
    },
    trim: true
  },

  // 📍 Business Profile Location ID (required when business_profile service is enabled)
  business_location_id: {
    type: String,
    required: false, // Only required when business_profile service is enabled
    validate: {
      validator: function(v) {
        // If business_profile is enabled, location_id must be present and non-empty
        if (this.service_type && this.service_type.includes('business_profile')) {
          return v && v.trim().length > 0;
        }
        return true;
      },
      message: 'Business Profile location ID is required when Business Profile service is enabled'
    },
    trim: true
  },

  // 💾 Business Profile Account Cache (prevent repeated API calls)
  business_accounts_cache: {
    type: Array,
    default: []
  },

  business_accounts_cached_at: {
    type: Date,
    default: null
  },

  // 📢 Google Ads Customer ID (required when google_ads service is enabled).
  // Digits-only account ID (no dashes), matching the format the Google Ads
  // API expects. Left unset by the OAuth callback itself — populated by the
  // account-selection step once that ships (mirrors business_account_id /
  // business_location_id, which are also filled in after connect, not at
  // token-exchange time).
  google_ads_customer_id: {
    type: String,
    required: false, // Only required when google_ads service is enabled
    validate: {
      validator: function(v) {
        if (this.service_type && this.service_type.includes('google_ads')) {
          return v && v.trim().length > 0;
        }
        return true;
      },
      message: 'Google Ads customer ID is required when Google Ads service is enabled'
    },
    trim: true
  },

  // 🏬 Google Ads Manager (MCC) Customer ID — the `login-customer-id` header
  // required on every Ads API call when the selected account sits under a
  // manager hierarchy. Optional even when google_ads is enabled, since not
  // every connected account has a manager.
  google_ads_login_customer_id: {
    type: String,
    default: null,
    trim: true
  },

  // 📛 Google Ads account display name (Gap #1, frontend integration audit).
  // Set at /select time (from the live validation call) and refreshed at
  // every /validate + every sync - the header needs this without a second
  // round-trip to re-list every accessible account just to find the one
  // already selected.
  google_ads_account_name: {
    type: String,
    default: null,
    trim: true
  },

  // 💱 Google Ads account currency (ISO 4217, e.g. 'INR', 'USD', 'EUR') -
  // same "set at /select, refreshed at /validate + every sync" pattern as
  // google_ads_account_name above. Single source of truth for every
  // monetary value the dashboard renders (see
  // frontend/contexts/GoogleAdsCurrencyContext.jsx) - the account's real
  // billing currency must never be assumed/hardcoded/inferred from browser
  // locale.
  google_ads_currency_code: {
    type: String,
    default: null,
    trim: true,
    uppercase: true
  },

  // ✅ Last time the selected Google Ads customer was successfully
  // re-validated against the live API (set by both the initial /select call
  // and the standalone /validate endpoint). Distinct from `last_used_at`
  // (touched by any successful Ads API call) and `connected_at` (OAuth
  // token issuance) - this answers "when did we last confirm the *selected
  // account* is still reachable", not just "when did we last talk to Google".
  google_ads_last_validated_at: {
    type: Date,
    default: null
  },

  // 🔄 Campaign metrics sync bookkeeping (Phase 6.3). Mirrors the
  // start/completed/failed timestamp triad the Job model already tracks per
  // *attempt*, but scoped to this connection's *last outcome of each kind* -
  // "when did a sync last actually succeed" survives across an intervening
  // failed attempt, which a single last_sync_at timestamp cannot express.
  google_ads_last_sync_started_at: {
    type: Date,
    default: null
  },
  // Phase 2 (Enterprise Historical Sync): set once the FULL historical
  // backfill (earliest campaign start date -> today) has completed at least
  // once. Distinct from google_ads_last_sync_completed_at (which reflects
  // the most recent sync of ANY kind, historical or incremental) - this
  // field is what googleAdsSyncService.computeHistoricalSyncWindow checks
  // to decide "deep historical backfill" vs "small trailing incremental
  // window" for the NEXT sync. Never cleared once set (a later incremental
  // sync never "un-syncs" history), so this is a one-way flag, not a
  // rolling timestamp like the others in this block.
  google_ads_history_synced_at: {
    type: Date,
    default: null
  },
  google_ads_last_sync_completed_at: {
    type: Date,
    default: null
  },
  google_ads_last_sync_failed_at: {
    type: Date,
    default: null
  },
  google_ads_last_sync_error: {
    type: String,
    default: null
  },
  google_ads_last_sync_duration_ms: {
    type: Number,
    default: null
  },
  // Per-run row counts from the last sync attempt (success or failure) -
  // populated by googleAdsSyncService, read by the /status endpoint.
  google_ads_last_sync_stats: {
    campaignsInserted: { type: Number, default: 0 },
    campaignsUpdated: { type: Number, default: 0 },
    campaignsRemoved: { type: Number, default: 0 },
    metricsUpserted: { type: Number, default: 0 },
    // Phase 6.4: search terms + optimization score are folded into this same
    // job as extra stages (see googleAdsSyncService.js) rather than getting
    // their own job type, since neither has its own refresh endpoint.
    searchTermsUpserted: { type: Number, default: 0 },
    optimizationScoreSynced: { type: Boolean, default: false },
    // Phase 6.5: device/geo/audience/ad/attribution/budget-alert sync are
    // ALL folded into this same job as further stages too - none of them
    // has its own dedicated refresh endpoint either (see Phase 6.5's API
    // Endpoints list), so none gets its own job type.
    devicePerformanceUpserted: { type: Number, default: 0 },
    geoPerformanceUpserted: { type: Number, default: 0 },
    audiencePerformanceUpserted: { type: Number, default: 0 },
    adsUpserted: { type: Number, default: 0 },
    conversionActionsUpserted: { type: Number, default: 0 },
    budgetAlertsGenerated: { type: Number, default: 0 }
  },

  // 🧭 Capability Matrix (Phase 6.5) - computed after every sync from
  // OBSERVED outcomes (did this sync stage succeed and return data), never
  // guessed by the frontend. See googleAdsCapabilityService.js for how each
  // flag is derived.
  // Each capability is a rich object, not a bare boolean (Gap #8, frontend
  // integration audit) - "the frontend should never guess why something is
  // unavailable" means `reason` must travel with `supported`, and
  // `availableSince` must survive across recomputations (see
  // googleAdsCapabilityService.computeAndPersistCapabilities, which reads
  // the PREVIOUS value here before overwriting, so a flag that flipped
  // true on sync #3 keeps that same date on sync #4 rather than resetting
  // to "now" every time).
  google_ads_capabilities: {
    supportsRecommendations: capabilityFieldSchema(),
    supportsOptimizationScore: capabilityFieldSchema(),
    supportsSearchTerms: capabilityFieldSchema(),
    supportsAudienceInsights: capabilityFieldSchema(),
    supportsAttribution: capabilityFieldSchema(),
    supportsBudgetForecast: capabilityFieldSchema(),
    supportsAdStrength: capabilityFieldSchema(),
    supportsPerformanceMax: capabilityFieldSchema(),
    computedAt: { type: Date, default: null }
  },

  // 🔄 Keyword sync bookkeeping (Phase 6.4) - identical shape to the
  // campaign sync triad above, its own job type (GOOGLE_ADS_KEYWORD_SYNC).
  google_ads_keyword_sync_started_at: { type: Date, default: null },
  google_ads_keyword_sync_completed_at: { type: Date, default: null },
  google_ads_keyword_sync_failed_at: { type: Date, default: null },
  google_ads_keyword_sync_error: { type: String, default: null },
  google_ads_keyword_sync_duration_ms: { type: Number, default: null },
  google_ads_keyword_sync_stats: {
    inserted: { type: Number, default: 0 },
    updated: { type: Number, default: 0 },
    removed: { type: Number, default: 0 }
  },

  // 🔄 Recommendation sync bookkeeping (Phase 6.4) - same shape, own job
  // type (GOOGLE_ADS_RECOMMENDATION_SYNC).
  google_ads_recommendation_sync_started_at: { type: Date, default: null },
  google_ads_recommendation_sync_completed_at: { type: Date, default: null },
  google_ads_recommendation_sync_failed_at: { type: Date, default: null },
  google_ads_recommendation_sync_error: { type: String, default: null },
  google_ads_recommendation_sync_duration_ms: { type: Number, default: null },
  google_ads_recommendation_sync_stats: {
    inserted: { type: Number, default: 0 },
    updated: { type: Number, default: 0 },
    resolved: { type: Number, default: 0 } // recommendations Google stopped returning
  },

  // 🔑 Google OAuth tokens - encrypted at rest (AES-256-GCM), transparently
  // decrypted on document read via the schema getter below. Never indexed:
  // there is no query need to search by token value, and indexing a secret
  // needlessly widens its exposure surface.
  refresh_token: {
    type: String,
    required: [true, 'Refresh token is required'],
    set: encryptToken,
    get: decryptToken
  },

  access_token: {
    type: String,
    default: null,
    set: encryptToken,
    get: decryptToken
  },

  token_expires_at: {
    type: Date,
    default: null
  },

  // 👤 Google account information
  google_email: {
    type: String,
    required: [true, 'Google email is required'],
    lowercase: true,
    trim: true
  },

  google_name: {
    type: String,
    required: [true, 'Google name is required'],
    trim: true
  },

  google_avatar: {
    type: String,
    default: null
  },

  // ⏰ Timestamps
  connected_at: {
    type: Date,
    default: Date.now
  },

  last_used_at: {
    type: Date,
    default: null
  },

  // 📊 Connection status
  status: {
    type: String,
    enum: ['active', 'revoked', 'expired'],
    default: 'active',
    index: true
  }

}, {
  timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' }
});

// Compound unique index on user_id, project_id, and purpose
googleConnectionSchema.index({ user_id: 1, project_id: 1, purpose: 1 }, { unique: true });

// Index for status filtering
googleConnectionSchema.index({ status: 1 });

// Index for user connections
googleConnectionSchema.index({ user_id: 1, status: 1 });

// Index for project connections
googleConnectionSchema.index({ project_id: 1, status: 1 });

// Static method to find active connection
googleConnectionSchema.statics.findActiveConnection = async function(userId, projectId, purpose = 'google_visibility') {
  return await this.findOne({
    user_id: userId,
    project_id: projectId,
    purpose: purpose,
    status: 'active'
  }).populate('user_id', 'email firstName lastName')
    .populate('project_id', 'project_name main_url');
};

// Static method to revoke connection
googleConnectionSchema.statics.revokeConnection = async function(userId, projectId, purpose = 'google_visibility') {
  return await this.updateOne(
    {
      user_id: userId,
      project_id: projectId,
      purpose: purpose,
      status: 'active'
    },
    {
      status: 'revoked',
      updated_at: new Date()
    }
  );
};

// Static method to update service types
googleConnectionSchema.statics.updateServiceTypes = async function(userId, projectId, serviceTypes, purpose = 'google_visibility') {
  return await this.updateOne(
    {
      user_id: userId,
      project_id: projectId,
      purpose: purpose,
      status: 'active'
    },
    {
      service_type: serviceTypes,
      updated_at: new Date()
    },
    { upsert: false }
  );
};

// Static method to update last sync timestamp
googleConnectionSchema.statics.updateLastSync = async function(userId, projectId, serviceType, purpose = 'google_visibility') {
  return await this.updateOne(
    {
      user_id: userId,
      project_id: projectId,
      purpose: purpose,
      status: 'active',
      service_type: serviceType
    },
    {
      last_sync_at: new Date(),
      updated_at: new Date()
    }
  );
};

// Static method to find connections by service type
googleConnectionSchema.statics.findByServiceType = async function(serviceType, purpose = 'google_visibility') {
  return await this.find({
    purpose: purpose,
    service_type: serviceType,
    status: 'active'
  }).populate('user_id', 'email firstName lastName')
    .populate('project_id', 'project_name main_url');
};

// Strip secrets from any serialized form of this document (res.json(doc),
// JSON.stringify(doc), console.log(doc.toObject()), etc.) - regardless of
// whether the underlying field is encrypted ciphertext or (legacy) plaintext.
function stripSecrets(doc, ret) {
  delete ret.refresh_token;
  delete ret.access_token;
  delete ret.__v;
  return ret;
}

googleConnectionSchema.set('toJSON', { virtuals: true, transform: stripSecrets });
googleConnectionSchema.set('toObject', { virtuals: true, transform: stripSecrets });

const GoogleConnection = mongoose.model('GoogleConnection', googleConnectionSchema);
export default GoogleConnection;
