import mongoose from 'mongoose';

const seoProjectSchema = new mongoose.Schema({
  // 🔐 Primary key (auto-generated by MongoDB)
  // _id: ObjectId (implicit)

  // 👤 Project owner
  user_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'User ID is required'],
    index: true
  },

  // 📌 Project Information
  project_name: {
    type: String,
    required: [true, 'Project name is required'],
    trim: true,
    minlength: [3, 'Project name must be at least 3 characters long'],
    maxlength: [100, 'Project name cannot exceed 100 characters'],
    match: [/^[a-zA-Z0-9\s\-_]+$/, 'Project name can only contain letters, numbers, spaces, hyphens, and underscores']
  },
  
  main_url: {
    type: String,
    required: [true, 'Main URL is required'],
    trim: true,
    lowercase: true,
    validate: {
      validator: function(url) {
        const urlRegex = /^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}(?:[-a-zA-Z0-9()@:%_\+.~#?&//=]*)$/;
        return urlRegex.test(url);
      },
      message: 'Please provide a valid URL starting with http:// or https://'
    }
  },

  business_type: {
    type: String,
    trim: true,
    maxlength: [200, 'Business type cannot exceed 200 characters'],
    default: null
  },

  industry: {
    type: String,
    trim: true,
    maxlength: [100, 'Industry cannot exceed 100 characters'],
    default: null
  },

  // 🎯 SEO Scope — persisted from onboarding targetLevel selection
  seo_scope: {
    type: String,
    enum: ['local', 'national'],
    default: null,
    index: true
  },

  // 🌍 Location & Language
  location: {
    type: String,
    trim: true,
    maxlength: [200, 'Location cannot exceed 200 characters'],
    default: null
  },

  country: {
    type: String,
    default: null,
    uppercase: true,
    minlength: 2,
    maxlength: 2
  },

  language: {
    type: String,
    default: 'en',
    lowercase: true,
    minlength: 2,
    maxlength: 5
  },

  // ⚙️ Status & Scheduling
  status: {
    type: String,
    enum: ['draft', 'active', 'paused', 'error'],
    default: 'draft',
    index: true
  },

  scrape_frequency: {
    type: String,
    enum: ['manual', 'daily', 'weekly', 'monthly'],
    default: 'manual'
  },

  // 🗑️ Soft delete (Project Trash & Restore, Phase 1)
  is_deleted: {
    type: Boolean,
    default: false,
    index: true
  },

  deleted_at: {
    type: Date,
    default: null
  },

  scheduled_purge_at: {
    type: Date,
    default: null
  },

  deleted_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },

  last_scraped_at: {
    type: Date,
    default: null
  },

  audit_started_at: {
    type: Date,
    default: null
  },

  last_analysis_at: {
    type: Date,
    default: null
  },

  // 🎯 SINGLE SOURCE OF TRUTH: Audit duration calculated from lifecycle timestamps
  audit_duration_ms: {
    type: Number,
    default: 0,
    min: 0 // Ensure non-negative duration
  },

  // 📊 SEO/Scraping Configuration
  keywords: {
    type: [String],
    required: [true, 'At least one keyword is required'],
    validate: {
      validator: function(keywords) {
        return keywords.length >= 1;
      },
      message: 'At least one keyword is required'
    }
  },

  description: {
    type: String,
    trim: true,
    maxlength: [500, 'Description cannot exceed 500 characters']
  },

  // 📊 Aggregated Metrics (Updated by workers only)
  total_pages: {
    type: Number,
    default: 0,
    min: 0
  },

  total_issues: {
    type: Number,
    default: 0,
    min: 0
  },

  // 📊 Detailed Crawl Metrics (NEW - from crawl summary)
  pages_discovered: {
    type: Number,
    default: 0,
    min: 0
  },

  pages_crawled: {
    type: Number,
    default: 0,
    min: 0
  },

  pages_analyzed: {
    type: Number,
    default: 0,
    min: 0
  },

  crawl_duration: {
    type: Number,
    default: 0,
    min: 0
  },

  crawl_success_rate: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },

  crawl_status: {
    type: String,
    enum: [
      'draft', 'pending', 'running', 'discovered',
      // awaiting_url_selection: URL_QUALIFICATION has completed and the
      // pipeline is parked, waiting for the user to review/approve which
      // discovered URLs get scraped (see UrlSelection model). No
      // PAGE_SCRAPING/HEADLESS_ACCESSIBILITY JobGroup exists yet for this
      // run while a project sits in this state.
      'awaiting_url_selection',
      'crawled', 'completed', 'failed', 'cancelled'
    ],
    default: 'pending'
  },

  // require_url_selection: feature flag gating the URL Selection workflow.
  // When true (default), URL_QUALIFICATION completing parks the pipeline in
  // 'awaiting_url_selection' instead of auto-creating PAGE_SCRAPING/
  // HEADLESS_ACCESSIBILITY JobGroups. Flipping this to false is the primary
  // rollback lever for the feature — no code change needed to revert to
  // fully-automatic URL selection.
  require_url_selection: {
    type: Boolean,
    default: true
  },

  // url_selection_limit: optional per-project cap enforced by
  // POST /url-selection. There is no platform-wide default — null (the
  // default for every project) means unlimited; a number here is an
  // explicit, intentional override for this one project only.
  url_selection_limit: {
    type: Number,
    default: null
  },

  // Host canonicalization: the redirect-resolved host of the seed URL as
  // determined by LINK_DISCOVERY for the most recent audit run (e.g.
  // "www.example.com" or "example.com" — whichever the site's own redirect
  // chain resolves to). Used as the single source of truth so www/non-www
  // (or other host-alias) duplicates never enter seo_internal_links.
  canonical_host: {
    type: String,
    default: null
  },

  canonical_url: {
    type: String,
    default: null
  },

  // current_run_id: the run_id of the audit execution currently in progress
  // (or most recently started) for this project — minted by
  // startProjectAudit()/startVerification(). Lets any query scope to "the
  // current run" instead of "this project across all historical runs".
  current_run_id: {
    type: mongoose.Schema.Types.ObjectId,
    default: null
  },

  last_crawl_summary: {
    type: Object,
    default: null
  },

  // 🤖 AI Visibility Data (Updated by AI visibility scoring worker)
  ai_visibility: {
    score: {
      type: Number
    },
    pages_scored: {
      type: Number
    },
    categories: {
      type: Object,
      default: {}
    },
    scoring_version: {
      type: String
    },
    summary: {
      type: String
    }
  },

  last_ai_analysis_at: {
    type: Date,
    default: null
  },

  // 🕒 System Timestamps (auto-managed by Mongoose)
  // created_at: Date (implicit)
  // updated_at: Date (implicit)

  // 🏢 Verified Business Information (from Google Places API)
  verified_business: {
    placeId: {
      type: String,
      required: false
    },
    name: {
      type: String,
      required: false
    },
    address: {
      type: String,
      required: false
    },
    city: {
      type: String,
      required: false,
      default: null
    },
    state: {
      type: String,
      required: false,
      default: null
    },
    country: {
      type: String,
      required: false,
      default: null
    },
    countryCode: {
      type: String,
      required: false,
      uppercase: true,
      minlength: 2,
      maxlength: 2,
      default: null
    },
    website: {
      type: String,
      required: false
    },
    phone: {
      type: String,
      required: false
    },
    rating: {
      type: Number,
      required: false,
      min: 0,
      max: 5
    },
    location: {
      lat: {
        type: Number,
        required: false
      },
      lng: {
        type: Number,
        required: false
      }
    },
    verifiedAt: {
      type: Date,
      required: false
    }
  },

  // Project source tracking
  source: {
    type: String,
    enum: ['web', 'external', 'api', 'migration', 'website_manual'],
    default: 'web'
  },

  // 🌐 Onboarding Mode Tracking (NEW — Website Manual Fallback)
  onboarding_mode: {
    type: String,
    enum: ['google_places', 'website_manual', 'external'],
    default: 'google_places'
  },

  discovery_source: {
    type: String,
    enum: ['google_places', 'website_scrape', 'manual_entry', 'external_api'],
    default: 'google_places'
  },

  // Reference to the Homepage Audit snapshot taken before project creation
  pre_audit_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'HomepageAudit',
    default: null,
    index: true
  },

  // Extracted website metadata (populated when onboarding_mode = 'website_manual')
  extracted_metadata: {
    title: { type: String, default: null },
    description: { type: String, default: null },
    og_tags: { type: Object, default: null },
    schema_org: { type: Object, default: null },
    social_links: { type: [String], default: [] },
    contact_info: {
      email: { type: String, default: null },
      phone: { type: String, default: null },
      address: { type: String, default: null }
    },
    confidence: { type: Number, default: 0, min: 0, max: 100 },
    extracted_at: { type: Date, default: null }
  },

  // 🎨 Brand Asset Resolution cache (see services/brandAssetService.js).
  // Website logo/favicon are resolved via a lightweight on-demand fetch of
  // main_url (cheerio, same pattern as businessDiscoveryService.js) and
  // cached here so the resolver doesn't re-fetch the site on every request -
  // resolveProjectBrandAssets() reads this first and only re-fetches once
  // resolved_at is older than its TTL (or a caller forces a refresh).
  // Google Business Profile logo (Priority 1) is NOT cached here - it's
  // read live from BusinessProfileMedia, which already has its own sync/cache.
  brand_assets: {
    website_logo_url: { type: String, default: null },
    website_logo_source: { type: String, default: null }, // 'schema:logo' | 'og:image'
    favicon_url: { type: String, default: null },
    favicon_source: { type: String, default: null }, // 'link:apple-touch-icon' | 'link:icon' | 'link:shortcut-icon' | 'favicon.ico'
    resolved_at: { type: Date, default: null }
  }

}, {
  timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' }
});

// Compound unique index on user_id and project_name
seoProjectSchema.index({ user_id: 1, project_name: 1 }, { unique: true });

// Index for status filtering
seoProjectSchema.index({ status: 1 });

// Index for created_at sorting
seoProjectSchema.index({ created_at: -1 });

// Index for scraping fields
seoProjectSchema.index({ last_scraped_at: -1 });
seoProjectSchema.index({ user_id: 1, last_scraped_at: -1 });
seoProjectSchema.index({ scrape_frequency: 1 });

// Index for crawl status and timing (NEW)
seoProjectSchema.index({ crawl_status: 1 });

// Index for trash queries (Project Trash & Restore, Phase 1)
seoProjectSchema.index({ user_id: 1, is_deleted: 1 });
seoProjectSchema.index({ audit_started_at: -1 });
seoProjectSchema.index({ last_analysis_at: -1 });
seoProjectSchema.index({ crawl_duration: -1 });
seoProjectSchema.index({ audit_duration_ms: -1 }); // 🎯 SINGLE SOURCE OF TRUTH INDEX

// Index for AI visibility analysis timing
seoProjectSchema.index({ last_ai_analysis_at: -1 });

// Index for business/industry filtering
seoProjectSchema.index({ industry: 1 });
seoProjectSchema.index({ country: 1 });
seoProjectSchema.index({ language: 1 });

// Index for onboarding mode analytics
seoProjectSchema.index({ onboarding_mode: 1 });

// Pre-save middleware to process keywords
seoProjectSchema.pre('save', function(next) {
  if (this.keywords && this.keywords.length > 0) {
    // Trim keywords and remove duplicates
    this.keywords = [...new Set(this.keywords.map(keyword => keyword.trim()).filter(keyword => keyword.length >= 2))];
  }
  next();
});

// Virtual for keyword count
seoProjectSchema.virtual('keyword_count', {
  get: function() {
    return (this.keywords || []).length;
  }
});

// Virtual for project age
seoProjectSchema.virtual('project_age_days', {
  get: function() {
    return Math.floor((Date.now() - this.created_at.getTime()) / (1000 * 60 * 60 * 24));
  }
});

// Virtual for days since last scrape
seoProjectSchema.virtual('days_since_last_scrape', {
  get: function() {
    if (!this.last_scraped_at) return null;
    return Math.floor((Date.now() - this.last_scraped_at.getTime()) / (1000 * 60 * 60 * 24));
  }
});

// Static method to update scraping results (worker-only)
seoProjectSchema.statics.updateScrapingResults = async function(projectId, results) {
  try {
    const updateData = {
      last_scraped_at: new Date(),
      total_pages: results.total_pages || 0,
      total_issues: results.total_issues || 0,
      updated_at: new Date()
    };

    return await this.findByIdAndUpdate(projectId, updateData, { new: true });
  } catch (error) {
    console.error('Error updating scraping results:', error);
    throw error;
  }
};

// Static method to get project scraping summary
seoProjectSchema.statics.getScrapingSummary = async function(projectId) {
  try {
    const project = await this.findById(projectId)
      .select('project_name main_url business_type industry location country language status scrape_frequency last_scraped_at total_pages total_issues created_at updated_at keyword_count')
      .lean();
    
    return project;
  } catch (error) {
    console.error('Error getting scraping summary:', error);
    throw error;
  }
};

// Static method to get projects by scraping frequency
seoProjectSchema.statics.getProjectsByFrequency = function(frequency) {
  return this.find({ scrape_frequency: frequency })
    .sort({ last_scraped_at: -1 })
    .populate('user_id', 'name email');
};

// Persists the resolved website logo/favicon (Priority 2/3 of the Brand
// Asset Resolver). Additive fields only - see brand_assets above.
seoProjectSchema.statics.updateBrandAssets = async function(projectId, fields) {
  return this.findByIdAndUpdate(
    projectId,
    { $set: { brand_assets: { ...fields, resolved_at: new Date() } } },
    { new: true }
  );
};

// Static method to get projects needing scraping
seoProjectSchema.statics.getProjectsNeedingScrape = function() {
  const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);

  return this.find({
    status: 'active',
    // Trashed projects (Project Trash & Restore, Phase 1) must never be
    // picked up by the scheduler — missing the field (pre-trash documents)
    // correctly falls on the "not deleted" side of $ne: true.
    is_deleted: { $ne: true },
    // $ne: 'manual' alone does NOT exclude legacy documents that predate this
    // field (missing entirely) — Mongo's $ne matches missing fields too, even
    // though the schema's `default: 'manual'` implies they should be treated
    // as manual. $nin: [null, 'manual'] excludes missing-field AND
    // explicit-null docs the same way it excludes 'manual' (verified: a
    // missing field also matches an explicit `null` query in MongoDB).
    scrape_frequency: { $nin: [null, 'manual'] },
    $or: [
      { last_scraped_at: { $lt: oneWeekAgo } },
      { last_scraped_at: null }
    ]
  }).sort({ last_scraped_at: 1, created_at: 1 });
};

// Ensure virtuals are included in JSON output
seoProjectSchema.set('toJSON', { virtuals: true });
seoProjectSchema.set('toObject', { virtuals: true });

const SeoProject = mongoose.model('SeoProject', seoProjectSchema);
export default SeoProject;
