import mongoose from 'mongoose';
import SeoProject from '../model/SeoProject.js';
import Job from '../../jobs/model/Job.js';
import { JobService } from '../../jobs/service/jobService.js';
import JobDispatcher from '../../jobs/service/jobDispatcher.js';
import auditProgressService from '../../jobs/service/auditProgressService.js';
import { ACTIVE_PIPELINE_JOB_TYPES } from './projectAuditService.js';
import { RUN_SOURCES } from '../../jobs/runSources.js';
import { LoggerUtil } from '../../../utils/LoggerUtil.js';

const getDb = () => mongoose.connection.db;
const jobService = new JobService();

/**
 * Result codes returned by startProjectVerification. Same convention as
 * AUDIT_RESULT_CODES: callers (HTTP controller, weekly scheduler) map these
 * to their own response/log format; this module never touches req/res.
 */
export const VERIFICATION_RESULT_CODES = {
  STARTED: 'STARTED',
  NOT_FOUND: 'NOT_FOUND',
  ACCESS_DENIED: 'ACCESS_DENIED',
  ALREADY_RUNNING: 'ALREADY_RUNNING',
  NO_PREVIOUS_CRAWL: 'NO_PREVIOUS_CRAWL',
};

const VERIFICATION_SOURCES = [RUN_SOURCES.MANUAL_RECHECK, RUN_SOURCES.WEEKLY_RECHECK];

/**
 * Soft reset — clear only collections regenerated during verification.
 * Preserves discovery data (seo_internal_links, crawl graph, domain performance,
 * keyword research, technical reports) so Quick Recheck can reuse them.
 *
 * Moved verbatim from scrapingController.js (behavior unchanged). NOTE for
 * weekly use: this runs BEFORE the new run has produced anything, so a run that
 * then fails leaves the project without page data/issues/scores until it is
 * re-audited — see the Weekly Recheck hand-off notes.
 */
export const softResetProjectCrawlData = async (projectId) => {
  try {
    const db = getDb();
    const { ObjectId } = mongoose.Types;
    const projectIdObj = new ObjectId(projectId);

    LoggerUtil.info(`Soft resetting verification data for project | projectId=${projectId}`);

    // Clear only collections regenerated by the verification pipeline.
    //
    // Preserved (never touched by Quick Recheck):
    //   seo_internal_links, seo_external_links, seo_social_links   — link discovery
    //   seo_crawl_graph                                             — crawl topology
    //   seo_domain_performance                                      — domain perf/pagespeed history
    //   seo_page_performance                                        — per-page pagespeed history
    //   seo_keyword_research, seo_keyword_opportunities             — keyword intelligence
    //   seo_rankings                                                — keyword ranking history
    //   search_console_data                                         — SERP tracking
    //   seo_first_snapshot, seo_mainurl_snapshot                    — audit snapshots
    //   audit_runs                                                  — audit history
    //
    // SEO collections (Node.js-written) use camelCase field 'projectId'.
    const collectionsToSoftClear = [
      'seo_page_data',     // regenerated by PAGE_SCRAPING
      'seo_page_issues',   // regenerated by PAGE_ANALYSIS
      'seo_page_scores',   // regenerated by SEO_SCORING
      'seo_page_summary',  // regenerated by SEO_SCORING
      'seo_headless_data', // regenerated by HEADLESS_ACCESSIBILITY
    ];

    // AI V2 collections (Python-written) use snake_case field 'project_id'.
    const aiV2CollectionsToSoftClear = [
      'ai_pages',
      'ai_scores',
      'ai_issues',
      'ai_projects',
    ];

    let totalDeleted = 0;
    for (const collectionName of collectionsToSoftClear) {
      const result = await db.collection(collectionName).deleteMany({ projectId: projectIdObj });
      totalDeleted += result.deletedCount;
      LoggerUtil.debug(`Soft cleared ${collectionName}`, { deleted: result.deletedCount });
    }
    for (const collectionName of aiV2CollectionsToSoftClear) {
      const result = await db.collection(collectionName).deleteMany({ project_id: projectIdObj });
      totalDeleted += result.deletedCount;
      LoggerUtil.debug(`Soft cleared ${collectionName}`, { deleted: result.deletedCount });
    }

    // 🔥 CRITICAL: Delete old Job records so the dependency gate does not find
    // stale PAGE_ANALYSIS jobs and silently skip creating new ones.
    const jobDeleteResult = await Job.deleteMany({ project_id: projectIdObj });
    totalDeleted += jobDeleteResult.deletedCount;
    LoggerUtil.info(`Soft reset: cleared old jobs`, { projectId, deleted: jobDeleteResult.deletedCount });

    // Reset verification-relevant project counters only
    await SeoProject.findByIdAndUpdate(projectId, {
      pages_crawled: 0,
      pages_analyzed: 0,
      total_issues: 0,
      crawl_status: 'pending',
      last_analysis_at: null
    });

    LoggerUtil.info(`Project soft reset complete`, { projectId, totalDeleted });
    return totalDeleted;

  } catch (error) {
    LoggerUtil.error(`Failed to soft reset crawl data`, error, { projectId });
    throw error;
  }
};

/**
 * Start the Quick Recheck (legacy project-wide verification) pipeline. This is
 * the ONE implementation — both POST /seo/start-verification (manual,
 * source 'manual_recheck') and the Weekly Recheck scheduler (source
 * 'weekly_recheck') call it. Do not duplicate any of this logic elsewhere.
 *
 * Skips LINK_DISCOVERY, URL_QUALIFICATION, DOMAIN_PERFORMANCE, KEYWORD_RESEARCH,
 * PERFORMANCE_MOBILE, and PERFORMANCE_DESKTOP. Reuses URLs from seo_page_data.
 * Runs: PAGE_SCRAPING → CRAWL_GRAPH + AI_VISIBILITY, HEADLESS_ACCESSIBILITY,
 *       then PAGE_ANALYSIS → SEO_SCORING.
 *
 * Billing: never checks or consumes any quota — neither project credits nor
 * manual recrawl credits. That is structural (this module does not import
 * creditService), not a per-source exemption.
 *
 * Locking: same atomic crawl_status claim + active-job guard as a Full Audit
 * (crawl_status 'running' AND 'awaiting_url_selection' both block it), so a
 * Recheck can never overlap a Full Audit/Recrawl on the same project.
 *
 * @param {string} projectId
 * @param {Object} options
 * @param {'manual_recheck'|'weekly_recheck'} [options.source='manual_recheck']
 * @param {string|mongoose.Types.ObjectId} [options.requestingUserId] - required for 'manual_recheck'; must own the project
 * @returns {Promise<{success:boolean, code:string, message?:string, data?:object}>}
 */
export async function startProjectVerification(projectId, options = {}) {
  const {
    source = RUN_SOURCES.MANUAL_RECHECK,
    requestingUserId = null,
  } = options;

  if (!VERIFICATION_SOURCES.includes(source)) {
    throw new Error(`startProjectVerification: invalid source '${source}'`);
  }

  const jobDispatcher = new JobDispatcher();

  const project = await SeoProject.findById(projectId);
  if (!project || project.is_deleted) {
    return { success: false, code: VERIFICATION_RESULT_CODES.NOT_FOUND, message: 'Project not found' };
  }

  // 🔒 SECURITY: ownership is only checked when a specific user requested the
  // run. A weekly run acts on behalf of the project's own owner.
  if (source === RUN_SOURCES.MANUAL_RECHECK) {
    if (!requestingUserId || project.user_id.toString() !== requestingUserId.toString()) {
      return { success: false, code: VERIFICATION_RESULT_CODES.ACCESS_DENIED, message: 'Access denied: You do not own this project' };
    }
  }

  // run_id: Quick Recheck mints its own fresh run_id too (per the approved
  // decision that verification mode stays single-job, no JobGroup/chunking,
  // but still gets run isolation). Stamped atomically alongside the claim.
  const runId = new mongoose.Types.ObjectId();

  // 🔒 ATOMIC IDEMPOTENCY GUARD: same pattern as startProjectAudit. Also
  // blocks on 'awaiting_url_selection' — a Full Audit parked at the URL
  // selection gate has no active job yet, and a recheck's soft reset would
  // wipe its jobs/state out from under it.
  const claimedProject = await SeoProject.findOneAndUpdate(
    { _id: projectId, crawl_status: { $nin: ['running', 'awaiting_url_selection'] } },
    { crawl_status: 'running', audit_started_at: new Date(), current_run_id: runId, current_run_source: source },
    { new: true }
  );

  if (!claimedProject) {
    return { success: false, code: VERIFICATION_RESULT_CODES.ALREADY_RUNNING, message: 'Scraping already in progress for this project' };
  }

  const releaseLock = () =>
    SeoProject.findByIdAndUpdate(projectId, { crawl_status: project.crawl_status || 'pending' });

  // Belt-and-suspenders: check for running pipeline jobs.
  // H3: reuses the shared ACTIVE_PIPELINE_JOB_TYPES (projectAuditService.js)
  // — also catches an in-flight Full Audit or URL Verification, not just
  // another legacy verification.
  const existingJobs = await jobService.getJobsByProject(projectId, {
    jobType: { $in: ACTIVE_PIPELINE_JOB_TYPES },
    status: { $in: ['pending', 'processing'] }
  });

  if (existingJobs.length > 0) {
    await releaseLock();
    return { success: false, code: VERIFICATION_RESULT_CODES.ALREADY_RUNNING, message: 'Verification already in progress for this project' };
  }

  // Load URLs from seo_page_data — these are pages that previously returned HTTP 200
  // and were successfully scraped. seo_internal_links may contain discovered-but-never-
  // scraped or dead URLs; seo_page_data is the authoritative set of live pages.
  const db = getDb();
  const { ObjectId } = mongoose.Types;
  const projectIdObj = new ObjectId(projectId);

  const pageDataDocs = await db.collection('seo_page_data')
    .find({ projectId: projectIdObj }, { projection: { url: 1 } })
    .toArray();

  const rawUrls = [...new Set(pageDataDocs.map(doc => doc.url).filter(Boolean))];

  if (rawUrls.length === 0) {
    await releaseLock();
    return {
      success: false,
      code: VERIFICATION_RESULT_CODES.NO_PREVIOUS_CRAWL,
      message: 'No previous crawl data found. Please run a Full Audit first.'
    };
  }

  // Always include project main URL; cap at 50 to bound worker load.
  // Normalize both sides before comparing — seo_page_data may store the homepage
  // with or without a trailing slash (e.g. "https://domain.com/" vs "https://domain.com"),
  // causing a strict .includes() to miss the match and inject both variants as separate URLs.
  const normalizeForCompare = (u) => u?.replace(/\/+$/, '').toLowerCase() ?? '';
  const normalizedMain = normalizeForCompare(project.main_url);
  const alreadyHasMain = rawUrls.some(u => normalizeForCompare(u) === normalizedMain);

  const withMain = alreadyHasMain
    ? rawUrls
    : [project.main_url, ...rawUrls];

  const finalUrls = withMain.slice(0, 50);

  LoggerUtil.info(`Starting verification for project | projectId=${projectId} | source=${source} | urls=${finalUrls.length}`);

  // Soft reset: clear verification-regenerated collections, preserve discovery data
  await softResetProjectCrawlData(projectId);

  // Create verification seed jobs — both receive the same canonical_urls list
  // so PAGE_SCRAPING and HEADLESS_ACCESSIBILITY process an identical URL set
  let pageScrapingJob, headlessA11yJob;
  try {
    pageScrapingJob = await jobService.createJob({
      user_id: project.user_id,
      seo_project_id: projectId,
      jobType: 'PAGE_SCRAPING',
      input_data: {
        mode: 'verification',
        run_source: source,
        canonical_urls: finalUrls,
        main_url: project.main_url
      },
      priority: 1,
      run_id: runId
    });

    headlessA11yJob = await jobService.createJob({
      user_id: project.user_id,
      seo_project_id: projectId,
      jobType: 'HEADLESS_ACCESSIBILITY',
      input_data: {
        mode: 'verification',
        run_source: source,
        canonical_urls: finalUrls,
        main_url: project.main_url,
        source_job_id: pageScrapingJob._id.toString()
      },
      priority: 1,
      run_id: runId
    });
  } catch (jobCreationError) {
    LoggerUtil.error('Verification job creation failed, releasing project lock', jobCreationError, { project_id: projectId, source });
    await releaseLock();
    throw jobCreationError;
  }

  // Mark project active
  await SeoProject.findByIdAndUpdate(projectId, { status: 'active' });

  // Dispatch both seed jobs asynchronously
  jobDispatcher.dispatchPageScrapingJob(pageScrapingJob).catch(error => {
    LoggerUtil.error(`Failed to dispatch PAGE_SCRAPING verification job ${pageScrapingJob._id}`, error);
  });

  jobDispatcher.dispatchHeadlessAccessibilityJob(headlessA11yJob).catch(error => {
    LoggerUtil.error(`Failed to dispatch HEADLESS_ACCESSIBILITY verification job ${headlessA11yJob._id}`, error);
  });

  // Emit started events so the frontend receives real-time updates
  auditProgressService.emitStarted(pageScrapingJob._id.toString(), {
    job_id: pageScrapingJob._id,
    job_type: pageScrapingJob.jobType,
    project_id: projectId,
    main_url: project.main_url,
    user_id: project.user_id,
    mode: 'verification',
    run_source: source
  });

  auditProgressService.emitStarted(headlessA11yJob._id.toString(), {
    job_id: headlessA11yJob._id,
    job_type: headlessA11yJob.jobType,
    project_id: projectId,
    main_url: project.main_url,
    user_id: project.user_id,
    mode: 'verification',
    run_source: source
  });

  return {
    success: true,
    code: VERIFICATION_RESULT_CODES.STARTED,
    data: {
      mode: 'verification',
      source,
      jobs: [
        {
          job_id: pageScrapingJob._id,
          job_type: pageScrapingJob.jobType,
          status: pageScrapingJob.status
        },
        {
          job_id: headlessA11yJob._id,
          job_type: headlessA11yJob.jobType,
          status: headlessA11yJob.status
        }
      ],
      url_count: finalUrls.length,
      project_id: projectId,
      main_url: project.main_url
    }
  };
}
